interface Window {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  appApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  navApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  searchResultsApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  conditionBuilderApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  detailModalApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  runtimePreApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  runtimeToolsApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  settingsPageApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  extensionsPageApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  containerViewApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  ratingsApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  sharePageApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  inspectPageApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  scanBannerApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  snsShareApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  bossLockApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  keyboardApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  storyPageApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  similarApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  unionSearchApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  toolsPageApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  runtimeInitApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  tagEditApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  dockApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  statsPageApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  promptHighlightApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  floatingGridApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  contextMenuApi?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  floatingGridApiCore?: Record<string, any> | null;
}
