"""Subcommand registration for tagdb CLI parser."""


def register_subcommands(sub, handlers):
    p_info = sub.add_parser("db-info", help="show database version and stats")
    p_info.add_argument("--db", required=True)
    p_info.set_defaults(func=handlers["cmd_db_info"])

    p_init = sub.add_parser("init", help="initialize database")
    p_init.add_argument("--db", required=True)
    p_init.set_defaults(func=handlers["cmd_init"])

    p_scan = sub.add_parser("scan", help="scan folder and index")
    p_scan.add_argument("--db", required=True)
    p_scan.add_argument("--root", required=True)
    p_scan.add_argument("--recursive", action="store_true", help="scan subdirectories recursively")
    p_scan.add_argument("--exts", default=".png,.jpg,.jpeg,.webp,.webm,.jxl,.avif,.heif,.heic,.svg,.pdf")
    p_scan.add_argument("--mark-deleted", action="store_true")
    p_scan.add_argument("--force", action="store_true", help="force re-parse even if unchanged")
    p_scan.add_argument("--compute-hash", action="store_true", help="compute ETag (SHA1 full or partial) to enable 304(not modified) skipping")
    p_scan.add_argument("--scan-zips", action="store_true", help="also scan images inside ZIP files")
    p_scan.set_defaults(func=handlers["cmd_scan"])

    p_scan_all = sub.add_parser("scan-all", help="scan all roots from config.json")
    p_scan_all.add_argument("--db", required=True)
    p_scan_all.add_argument("--force", action="store_true", help="force re-parse even if unchanged")
    p_scan_all.add_argument("--scan-zips", action="store_true", help="also scan images inside ZIP files")
    p_scan_all.set_defaults(func=handlers["cmd_scan_all"])

    p_add_root = sub.add_parser("add-root", help="add scan root to config.json")
    p_add_root.add_argument("path", help="directory path to add")
    p_add_root.add_argument("--recursive", dest="recursive", action="store_true", default=True, help="scan recursively (default)")
    p_add_root.add_argument("--no-recursive", dest="recursive", action="store_false", help="scan only the specified directory")
    p_add_root.add_argument("--enabled", dest="enabled", action="store_true", default=True, help="enable this root (default)")
    p_add_root.add_argument("--disabled", dest="enabled", action="store_false", help="add this root as disabled")
    p_add_root.add_argument("--comment", default="", help="optional comment")
    p_add_root.set_defaults(func=handlers["cmd_add_root"])

    p_list_roots = sub.add_parser("list-roots", help="list all scan roots from config.json")
    p_list_roots.set_defaults(func=handlers["cmd_list_roots"])

    p_remove_root = sub.add_parser("remove-root", help="remove scan root from config.json")
    p_remove_root.add_argument("path", help="directory path to remove")
    p_remove_root.set_defaults(func=handlers["cmd_remove_root"])

    p_search = sub.add_parser("search", help="search indexed files by tag, prompt, filename, etc.")
    p_search.add_argument("--db", required=True, help="path to SQLite database")
    p_search.add_argument("--q", default=None, help="tag search (comma-separated, prefix with - to exclude)")
    p_search.add_argument("--artist", default=None, help="filter by artist namespace")
    p_search.add_argument("--in-prompt", default=None, help="full-text search in raw prompt")
    p_search.add_argument("--file-name", default=None, help="search by filename or directory path")
    p_search.add_argument("--checkpoint", default=None, help="filter by model/checkpoint name or hash")
    p_search.add_argument("--regex", action="store_true", help="treat search terms as regular expressions")
    p_search.add_argument("--from", dest="from_date", default=None, help="start date (YYYY-MM-DD)")
    p_search.add_argument("--to", dest="to_date", default=None, help="end date (YYYY-MM-DD)")
    p_search.add_argument("--limit", default=50, type=int, help="max results (default: 50)")
    p_search.set_defaults(func=handlers["cmd_search"])

    p_clean = sub.add_parser("cleanup", help="cleanup / dedupe DB")
    p_clean.add_argument("--db", required=True)
    p_clean.add_argument("--dedupe-paths", action="store_true")
    p_clean.add_argument("--prune-unused-tags", action="store_true")
    p_clean.add_argument("--mark-missing", action="store_true")
    p_clean.add_argument("--normalize-tags", action="store_true", help="normalize and merge duplicate tags (e.g. 'tag,' -> 'tag')")
    p_clean.add_argument("--vacuum", action="store_true")
    p_clean.add_argument("--dry-run", action="store_true")
    p_clean.set_defaults(func=handlers["cmd_cleanup"])

    p_dupes = sub.add_parser("find-duplicates", help="find duplicate files")
    p_dupes.add_argument("--db", required=True)
    p_dupes.add_argument("--by-hash", action="store_true", help="find by content hash (accurate)")
    p_dupes.add_argument("--by-size", action="store_true", help="find by file size (fast but less accurate)")
    p_dupes.add_argument("--cross-directory", action="store_true", help="only show duplicates in different directories")
    p_dupes.add_argument("--delete", action="store_true", help="delete duplicates (keeps first occurrence)")
    p_dupes.set_defaults(func=handlers["cmd_find_duplicates"])
