"""Default application configuration values."""

DEFAULT_CONFIG = {
    "timezone": None,
    "ui": None,
    "direct_prompt_convert": False,
    "preserve_templates": True,
    "brace_choice": False,
    "extract_comfyui": True,
    "extract_a1111": True,
    "enable_fts": True,
    "lowercase_tags": True,
    "compute_hash": False,
    "archive_throttle_ms": 20,
    "media_cache": {
        "l1_max_items": 20000,
        "l1_max_mb": 512,
    },
    "server": {
        "host": "127.0.0.1",
        "port": 5000,
        "lan": False,
        "pin": None,
        "pin_boss_login_ui": True,
        "quick_lock_enabled": True,
        "allow_restart": False,
        "allow_remote_restart": False,
        "restart_token": None,
    },
    "remote_fs": {
        "probe_retries": 6,
        "probe_wait": 5.0,
        "enumerate_retries": 5,
        "enumerate_wait": 10.0,
    },
    "scan_exclude_dirs": [
        ".git", ".svn", ".hg",
        "node_modules", "__pycache__", ".pytest_cache",
        "venv", ".venv", "env",
        "site-packages", "dist-packages",
        "custom_nodes", "extensions", "extensions-builtin",
        "screenshots", "reports",
    ],
    "video_analysis": {
        "enabled": True,
        "keyframe_count": 4,
        "strategy": "uniform",
        "scene_threshold": 0.4,
        "store_per_keyframe": False,
    },
    "inference_worker": {
        "enabled": False,
    },
    "hailo": {
        "auto_reboot": {
            "mode": "off",
            "dry_run": False,
            "prewarn_threshold_mb": 80,
            "prewarn_duration_seconds": 180,
            "drain_threshold_mb": 30,
            "drain_duration_seconds": 60,
            "drain_consecutive_rejects": 3,
            "fire_grace_seconds": 120,
            "poll_interval_seconds": 30,
            "min_uptime_minutes": 30,
            "max_reboots_per_day": 4,
            "cooldown_minutes": 15,
        },
    },
    "hailo_genai": {
        "llm_subprocess": False,
    },
    "api_keys": [],
    "webhooks": [],
    "webhook_secret": None,
    "backup": {
        "enabled": True,
        "backup_dir": "",
        "max_generations": 5,
        "periodic_interval_hours": 24,
        "backup_on_scan_complete": True,
        "cooldown_minutes": 5,
    },
    "scheduler": {
        "enabled": True,
        "jobs": {
            "db_vacuum": {
                "enabled": True,
                "trigger": "cron",
                "day_of_week": "sun",
                "hour": 3,
                "minute": 0,
            },
            "db_integrity_check": {
                "enabled": True,
                "trigger": "cron",
                "hour": 4,
                "minute": 0,
            },
            "thumbnail_cleanup": {
                "enabled": True,
                "trigger": "cron",
                "hour": 5,
                "minute": 0,
            },
            "thumbnail_cleanup_pressure": {
                "enabled": True,
                "trigger": "interval",
                "hours": 4,
            },
            "thumbnail_integrity_check": {
                "enabled": True,
                "trigger": "cron",
                "day_of_week": "sat",
                "hour": 4,
                "minute": 30,
            },
            "extension_audit_periodic": {
                "enabled": True,
                "trigger": "cron",
                "day_of_week": "wed",
                "hour": 2,
                "minute": 30,
            },
            "extension_audit_surprise": {
                "enabled": True,
                "trigger": "interval",
                "hours": 6,
                "jitter": 3600,
            },
        },
    },
    "agent_safety": {
        "circuit_breaker": {
            "enabled": True,
            "max_actions_per_minute": 60,
            "max_identical_consecutive": 3,
            "max_same_tool_per_minute": 15,
            "max_consecutive_errors": 10,
            "error_rate_threshold": 0.5,
            "cooldown_seconds": 60,
        },
        "budget": {
            "preset": "standard",
        },
    },
}
