use std::sync::Arc;

use axum::{extract::State, http::StatusCode, response::IntoResponse, Json};
use serde::Deserialize;
use serde_json::json;

use crate::state::SharedState;

#[derive(Deserialize)]
pub struct InferRequest {
    pub path: String,
    pub model_id: String,
    #[serde(default = "default_general_thr")]
    pub general_thr: f32,
    #[serde(default = "default_character_thr")]
    pub character_thr: f32,
}

fn default_general_thr() -> f32 {
    0.35
}
fn default_character_thr() -> f32 {
    0.85
}

pub fn should_use_infer_client(infer_client_present: bool) -> bool {
    infer_client_present
}

pub(crate) enum WdInferOutcome {
    Success(infer_core::engine::TagResult),
    /// canonicalize failure, or scan_roots rejection (fail-closed: always
    /// rejected when scan_roots is empty, too).
    PathRejected,
    ModelNotDownloaded,
    BackendError(String),
    Unreachable(String),
}

/// Canonicalizes a user-supplied path and validates it against scan_roots
/// (fail-closed) before dispatching WD inference. Both `wd_infer::infer`
/// (the raw bridge route) and the upcoming native WD-Tagger v1.5 route call
/// this function; HTTP response conversion is left to each caller.
pub(crate) async fn call_wd_infer(
    state: &SharedState,
    path: &std::path::Path,
    model_id: &str,
    general_thr: f32,
    character_thr: f32,
) -> WdInferOutcome {
    let real_path = match validate_wd_infer_path(state, path) {
        Ok(path) => path,
        Err(()) => return WdInferOutcome::PathRejected,
    };

    dispatch_wd_infer(state, &real_path, model_id, general_thr, character_thr).await
}

/// Canonicalizes a user-supplied path and checks the fail-closed scan-root policy.
pub(crate) fn validate_wd_infer_path(
    state: &SharedState,
    path: &std::path::Path,
) -> Result<std::path::PathBuf, ()> {
    let real_path = std::fs::canonicalize(path).map_err(|_| ())?;

    let scan_roots: Vec<std::path::PathBuf> = state
        .config
        .app_config
        .get("scan_roots")
        .and_then(|v| v.as_array())
        .map(|arr| {
            arr.iter()
                .filter_map(|r| r.get("path").and_then(|p| p.as_str()))
                .filter_map(|p| std::fs::canonicalize(p).ok())
                .collect()
        })
        .unwrap_or_default();
    // fail-closed: an empty scan_roots configuration always denies, matching
    // the yu-infer sidecar's own policy (previously this local check allowed
    // everything when scan_roots was empty).
    if scan_roots.is_empty() || !scan_roots.iter().any(|root| real_path.starts_with(root)) {
        return Err(());
    }

    Ok(real_path)
}

/// Calls WD inference for a temporary file generated by this process itself
/// (for example, an ffmpeg-extracted video frame). This must never receive a
/// user-supplied path because it skips the scan_roots security check.
pub(crate) async fn call_wd_infer_temp_frame(
    state: &SharedState,
    frame_path: &std::path::Path,
    model_id: &str,
    general_thr: f32,
    character_thr: f32,
) -> WdInferOutcome {
    let real_path = match std::fs::canonicalize(frame_path) {
        Ok(p) => p,
        Err(_) => return WdInferOutcome::PathRejected,
    };

    dispatch_wd_infer(state, &real_path, model_id, general_thr, character_thr).await
}

/// Find the profile whose cache directory is `model_id` and turn it into the
/// recipe the sidecar runs.
///
/// Resolved here rather than at each call site: every WD entry point —
/// single-file tagging, retag, batch, video keyframes — funnels through this
/// function, and a call site that forgot to pass the profile would silently
/// run the built-in WD recipe against another family's weights.
pub(crate) fn resolve_wire_profile(
    state: &SharedState,
    model_id: &str,
    general_thr: f32,
    character_thr: f32,
) -> Option<(serde_json::Value, Option<String>)> {
    let profiles = crate::routes::wd_tagger::load_full_profiles(&state.config.project_root);
    let (profile, _, _) = profiles.values().find(|(profile, _, _)| {
        profile
            .get("model_id")
            .and_then(|v| v.as_str())
            .map(crate::routes::wd_tagger_infer::sanitize_model_id)
            .as_deref()
            == Some(model_id)
    })?;
    let wire = crate::wd_profile_wire::wire_profile(profile, general_thr, character_thr)?;
    // Variant repos keep their builds in a subdirectory of the cache entry;
    // the recipe alone does not say which one.
    let subdir = profile
        .get("hf_subdir")
        .and_then(|v| v.as_str())
        .filter(|s| !s.is_empty())
        .map(str::to_string);
    Some((wire, subdir))
}

async fn dispatch_wd_infer(
    state: &SharedState,
    real_path: &std::path::Path,
    model_id: &str,
    general_thr: f32,
    character_thr: f32,
) -> WdInferOutcome {
    if model_id.contains('/') || model_id.contains('\\') || model_id.contains("..") {
        return WdInferOutcome::PathRejected;
    }

    let resolved = resolve_wire_profile(state, model_id, general_thr, character_thr);
    let wire = resolved.as_ref().map(|(wire, _)| wire);
    let model_subdir = resolved.as_ref().and_then(|(_, subdir)| subdir.as_deref());

    if should_use_infer_client(state.infer_client.is_some()) {
        let infer_client = state.infer_client.as_ref().expect("checked is_some above");
        let Some(real_path_str) = real_path.to_str() else {
            return WdInferOutcome::PathRejected;
        };
        return match infer_client
            .infer_wd(
                real_path_str,
                model_id,
                general_thr,
                character_thr,
                wire,
                model_subdir,
            )
            .await
        {
            Ok(value) => {
                // A sidecar predating the profile field ignores it and runs the
                // built-in WD recipe, which for another family yields confident
                // wrong tags rather than an error. Refuse the answer instead of
                // storing it.
                if wire.is_some()
                    && value.get("profile_applied").and_then(|v| v.as_bool()) != Some(true)
                {
                    return WdInferOutcome::BackendError(
                        "yu-infer did not apply the model profile; update the sidecar".to_string(),
                    );
                }
                match serde_json::from_value::<infer_core::engine::TagResult>(
                    value.get("data").cloned().unwrap_or(serde_json::json!({})),
                ) {
                    Ok(result) => WdInferOutcome::Success(result),
                    Err(e) => WdInferOutcome::BackendError(e.to_string()),
                }
            }
            Err(crate::infer_client::InferClientError::BadStatus { status, body })
                if status == StatusCode::SERVICE_UNAVAILABLE.as_u16() =>
            {
                tracing::warn!("yu-infer reports model not downloaded: {body}");
                WdInferOutcome::ModelNotDownloaded
            }
            Err(crate::infer_client::InferClientError::BadStatus { status, body }) => {
                tracing::error!("yu-infer returned {status}: {body}");
                WdInferOutcome::BackendError(body)
            }
            Err(e) => {
                tracing::error!("yu-infer request failed: {e}");
                WdInferOutcome::Unreachable(e.to_string())
            }
        };
    }

    let wd_cache = state.config.cache_dir.join("wd_tagger");
    let Some(model_dir) = infer_core::resolve_model_dir(&wd_cache, model_id, model_subdir) else {
        return WdInferOutcome::PathRejected;
    };

    let spec: infer_core::WdProfileSpec = match wire {
        Some(wire) => match serde_json::from_value(wire.clone()) {
            Ok(spec) => spec,
            Err(e) => return WdInferOutcome::BackendError(format!("invalid model profile: {e}")),
        },
        None => infer_core::builtin_wd_profile("model.onnx", general_thr, character_thr),
    };
    if !infer_core::is_profile_model_ready(&model_dir, &spec) {
        return WdInferOutcome::ModelNotDownloaded;
    }

    // The engine caches the vocabulary, thresholds and preprocess recipe, so
    // the cache is keyed by the resolved profile as well as the directory.
    // A single OnceLock here used to pin the first model loaded for the life
    // of the process, which no test noticed because nothing switched models.
    let cache_key = match serde_json::to_string(&spec) {
        Ok(fingerprint) => format!("{}\x00{fingerprint}", model_dir.display()),
        Err(e) => return WdInferOutcome::BackendError(format!("profile fingerprint: {e}")),
    };
    let engines = state.wd_infer.clone();
    let real_path = real_path.to_path_buf();
    let result = tokio::task::spawn_blocking(move || {
        let engine = {
            let mut guard = engines.lock().expect("wd engine cache not poisoned");
            match guard.get(&cache_key) {
                Some(engine) => Arc::clone(engine),
                None => {
                    let engine = Arc::new(infer_core::WdInferEngine::new(&model_dir, spec)?);
                    guard.insert(cache_key, Arc::clone(&engine));
                    engine
                }
            }
        };
        engine.run(&real_path)
    })
    .await;

    match result {
        Ok(Ok(tag_result)) => WdInferOutcome::Success(tag_result),
        Ok(Err(e)) => {
            tracing::error!("infer error: {e}");
            WdInferOutcome::BackendError(e.to_string())
        }
        Err(e) => {
            tracing::error!("spawn_blocking panic: {e}");
            WdInferOutcome::Unreachable(e.to_string())
        }
    }
}

pub async fn infer(
    State(state): State<SharedState>,
    Json(body): Json<InferRequest>,
) -> impl IntoResponse {
    match call_wd_infer(
        &state,
        std::path::Path::new(&body.path),
        &body.model_id,
        body.general_thr,
        body.character_thr,
    )
    .await
    {
        WdInferOutcome::Success(tag_result) => {
            Json(json!({"ok": true, "data": tag_result})).into_response()
        }
        WdInferOutcome::PathRejected => (
            StatusCode::FORBIDDEN,
            Json(json!({"error": "path outside allowed roots"})),
        )
            .into_response(),
        WdInferOutcome::ModelNotDownloaded => (
            StatusCode::SERVICE_UNAVAILABLE,
            Json(json!({"error": "model not downloaded"})),
        )
            .into_response(),
        WdInferOutcome::BackendError(_) => (
            StatusCode::BAD_GATEWAY,
            Json(json!({"error": "inference backend error"})),
        )
            .into_response(),
        WdInferOutcome::Unreachable(_) => (
            StatusCode::BAD_GATEWAY,
            Json(json!({"error": "inference backend unreachable"})),
        )
            .into_response(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::{
        collections::HashSet,
        str::FromStr,
        sync::Arc,
        time::{SystemTime, UNIX_EPOCH},
    };

    use axum::response::IntoResponse;
    use serde_json::json;
    use sqlx::sqlite::{SqliteConnectOptions, SqlitePoolOptions};

    use crate::state::{AppState, Config};

    #[test]
    fn uses_infer_client_when_present() {
        assert!(should_use_infer_client(true));
    }

    #[test]
    fn uses_fallback_when_absent() {
        assert!(!should_use_infer_client(false));
    }

    async fn test_state(app_config: serde_json::Value) -> SharedState {
        let suffix = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let root = std::env::temp_dir().join(format!("yu-server-wd-infer-test-{suffix}"));
        std::fs::create_dir_all(&root).unwrap();

        let pool = SqlitePoolOptions::new()
            .connect_with(SqliteConnectOptions::from_str("sqlite::memory:").unwrap())
            .await
            .unwrap();

        Arc::new(
            AppState::new(
                Config {
                    db_path: "sqlite::memory:".to_string(),
                    pin_hash: String::new(),
                    valid_token: String::new(),
                    secret: String::new(),
                    trusted_proxy_enabled: false,

                    pin_boss_login_ui: false,
                    trusted_ips: HashSet::new(),
                    trusted_peer_ips: HashSet::new(),
                    quick_lock_enabled: true,
                    pin_auth_enabled: false,
                    min_pin_length: 4,
                    python_url: String::new(),
                    config_path: root.join("config.json"),
                    project_root: root.clone(),
                    app_config,
                    cache_dir: root.join("cache"),
                    server_mode: "full".to_string(),
                    headless: false,
                    safe_mode: false,
                    mcp_native: false,
                    standalone: false,
                    infer_standalone: true,
                    active_profile: None,
                    python_executable: String::new(),
                },
                pool.clone(),
                pool,
                Arc::new(crate::logs::ring::LogRingBuffer::new(64)),
            )
            .await,
        )
    }

    #[tokio::test]
    async fn infer_rejects_when_scan_roots_is_empty() {
        // fail-closed方針への変更: 従来は空 scan_rootsで無条件許可だったが、
        // 本タスク以降は空scan_rootsで常に拒否(403)する。
        let dir = std::env::temp_dir().join("wd-infer-empty-scanroots-test");
        std::fs::create_dir_all(&dir).unwrap();
        let file_path = dir.join("test.png");
        std::fs::write(&file_path, b"fake").unwrap();

        // scan_rootsは空(既定)のまま呼び出す
        let state = test_state(json!({})).await;
        let body = InferRequest {
            path: file_path.to_str().unwrap().to_string(),
            model_id: "wd_vit_v3".to_string(),
            general_thr: 0.35,
            character_thr: 0.85,
        };
        let response = infer(axum::extract::State(state), axum::Json(body))
            .await
            .into_response();
        assert_eq!(response.status(), axum::http::StatusCode::FORBIDDEN);

        std::fs::remove_file(&file_path).ok();
    }
}
