#!/usr/bin/env python3
"""Generate byte-compat test vectors for the Rust peer-transport auth port.

Imports the REAL Python crypto functions (token scrypt hash, canonical signing
string, Ed25519 sign, nonce classification) and emits ground-truth vectors so
the Rust implementation (Increment A) can be pinned to Python exactly. This
resolves the inventory contradiction on scrypt dklen (design MF-1).

Run:  uv run python scripts/gen_peer_transport_vectors.py
Output: tests/vectors/peer_transport_vectors.json (consumed by Rust unit tests)
"""
from __future__ import annotations

import base64
import hashlib
import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import sys

from lan_cowork_repo import vectors_dir  # noqa: E402

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from core.crypto_identity.keypair import ed25519_pubkey_bytes, sign
from core.crypto_identity.request_signer import (
    NONCE_REQUIRED_PREFIXES,
    NONCE_REQUIRED_SUFFIXES,
    build_canonical_message,
    path_requires_nonce,
)
from extensions.builtin_lan_cowork.core_impl.token_store import (
    _SCRYPT_MAXMEM,
    _SCRYPT_N,
    _SCRYPT_P,
    _SCRYPT_R,
    _hash_token,
)

# Deterministic 32-byte Ed25519 seed → reproducible signature (Ed25519 is
# deterministic per RFC 8032, so the same seed+message always yields the same
# signature). Bytes 1..32.
SEED = bytes(range(1, 33))


def token_vectors() -> dict:
    raw = "peer-token-vector-001"
    digest = _hash_token(raw)
    return {
        "params": {"n": _SCRYPT_N, "r": _SCRYPT_R, "p": _SCRYPT_P, "maxmem": _SCRYPT_MAXMEM},
        "salt_utf8": "yu-ai-peer-token",
        "raw": raw,
        "hash_hex": digest,
        "hash_hex_len": len(digest),
        "dklen_bytes": len(digest) // 2,
    }


def signature_vectors() -> list[dict]:
    pubkey = ed25519_pubkey_bytes(SEED)
    cases = [
        # (method, path, query_string, body, ts_str)
        ("DELETE", "/ext/lan_cowork/api/peer/abcd1234ef567890", "", b"", "1700000000"),
        ("POST", "/ext/lan_cowork/api/peer/message", "foo=bar", b'{"x":1}', "1700000123"),
        ("GET", "/ext/lan_cowork/api/peer/status", "", b"", "1700000456"),
    ]
    out = []
    for method, path, qs, body, ts in cases:
        canonical = build_canonical_message(method, path, qs, ts, body)
        sig = sign(SEED, canonical)
        out.append(
            {
                "method": method,
                "path": path,
                "query_string": qs,
                "body_utf8": body.decode("utf-8"),
                "ts": ts,
                "body_sha256_hex": hashlib.sha256(body or b"").hexdigest(),
                "canonical_hex": canonical.hex(),
                "sig_b64url": base64.urlsafe_b64encode(sig).decode("ascii"),
            }
        )
    return {
        "seed_hex": SEED.hex(),
        "pubkey_hex": pubkey.hex(),
        "cases": out,
    }


def nonce_classification() -> dict:
    probe = [
        "/ext/lan_cowork/api/peer/message",
        "/ext/lan_cowork/api/peer/token/renew",
        "/ext/lan_cowork/api/peer/negotiate",
        "/ext/lan_cowork/api/peer/infer/wd",
        "/ext/lan_cowork/api/peer/import/session",
        "/ext/lan_cowork/fleet/restart",
        "/ext/lan_cowork/api/peer/status",
        "/ext/lan_cowork/api/peer/abcd1234",
    ]
    return {
        "suffixes": list(NONCE_REQUIRED_SUFFIXES),
        "prefixes": list(NONCE_REQUIRED_PREFIXES),
        "probe": {p: path_requires_nonce(p) for p in probe},
    }


def main() -> None:
    vectors = {
        "_note": "Generated by scripts/gen_peer_transport_vectors.py from the real "
        "Python crypto. Do not edit by hand. Rust peer-transport tests assert "
        "byte-equality against these (design 2026-07-19 MF-1/SF-1).",
        "token_scrypt": token_vectors(),
        "request_signature": signature_vectors(),
        "nonce": nonce_classification(),
        "timestamp_tolerance_s": 30,
        "nonce_grace_s": 60,
    }
    out_path = vectors_dir() / "peer_transport_vectors.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(vectors, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {out_path}")
    print(f"token hash: {vectors['token_scrypt']['hash_hex_len']} hex chars "
          f"({vectors['token_scrypt']['dklen_bytes']} bytes)")
    print(f"pubkey: {vectors['request_signature']['pubkey_hex']}")


if __name__ == "__main__":
    main()
