"""Generate FEATURES.md from extensions/*/extension.json (deterministic, no I/O beyond files)."""
from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUTPUT = REPO / "FEATURES.md"

sys.path.insert(0, str(REPO))
from core.extensions_core.lifecycle.extensions_loader_manifest import load_manifest  # noqa: E402

# Category display order (mirrors /api/extensions category_order intent).
CATEGORY_ORDER = ["ai", "metadata", "bridge", "prompt", "library", "system"]

def collect_manifests(ext_root: Path):
    out = []
    for d in sorted(ext_root.iterdir()):
        if d.is_dir():
            m = load_manifest(d)
            if m:
                out.append(m)
    return sorted(out, key=lambda m: m.name)

def _escape_cell(value: str) -> str:
    return str(value).replace("|", "\\|")

def _config_rows(m):
    schema = getattr(m, "config_schema", None) or {}
    rows = []
    for key in sorted(schema):
        f = schema[key]
        typ = getattr(f, "type", "")
        default = _escape_cell(getattr(f, "default", None))
        flag = _escape_cell(getattr(f, "cli_flag", None) or "")
        desc = _escape_cell(getattr(f, "description", None) or getattr(f, "label", None) or "")
        rows.append(f"| `{key}` | {typ} | `{default}` | {flag} | {desc} |")
    return rows

def render_markdown(manifests) -> str:
    by_cat: dict[str, list] = {}
    for m in manifests:
        by_cat.setdefault(m.category or "other", []).append(m)
    ordered = CATEGORY_ORDER + sorted(c for c in by_cat if c not in CATEGORY_ORDER)
    lines = [
        "<!-- GENERATED by scripts/gen_feature_index.py -- do not edit by hand. -->",
        "# Features",
        "",
        f"{len(manifests)} built-in extensions. Configuration details per feature below; "
        "see the per-feature docs for full setup.",
        "",
    ]
    seen = set()
    for cat in ordered:
        items = by_cat.get(cat)
        if not items or cat in seen:
            continue
        seen.add(cat)
        lines.append(f"## {cat}")
        lines.append("")
        for m in items:
            lines.append(f"### {m.name}")
            lines.append("")
            lines.append(m.description or "")
            lines.append("")
            rows = _config_rows(m)
            if rows:
                lines.append("")
                lines.append("| key | type | default | cli flag | description |")
                lines.append("|-----|------|---------|----------|-------------|")
                lines.extend(rows)
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"

def main(argv) -> int:
    manifests = collect_manifests(REPO / "extensions")
    content = render_markdown(manifests)
    if "--check" in argv:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != content:
            print("FEATURES.md is stale -- run: uv run python scripts/gen_feature_index.py", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO)} ({len(manifests)} extensions)")
    return 0

if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
