#!/usr/bin/env python3
"""Generate the Rust migration route inventory from Python route registrations.

Output: docs/development/rust-migration-inventory.yaml
Each entry: path, methods, handler, file, core_deps, status, batch.
Existing status/batch values are preserved across regeneration.

CAUTION -- what ``status`` does and does not mean:

  ``status`` is NOT measured against the Rust sources. It is carried over from the
  previous YAML (see ``carry_over_status``) and only ever promoted to ``native`` by
  the hand-maintained ``NATIVE_ROUTES`` / ``NATIVE_PREFIXES`` tables below. A route
  whose Rust handler landed without someone editing those tables keeps its stale
  ``proxied`` label forever. A 2026-08-19 cross-check found 22 of the 50 non-native
  entries were in fact already registered in ``main.rs``.

  This file also only sees routes that still have a Python definition, so an endpoint
  disappears from the ledger once its Python side is removed. ``total`` therefore
  counts "endpoints still defined in Python", not "all endpoints", and completed work
  becomes invisible here rather than showing up as progress.

  For the residual Python dependency measured from the Rust sources, use
  ``docs/development/rust-python-forwarders.txt`` (generated by
  ``scripts/internal/rust_python_forwarders.py``), which enumerates the handlers that
  actually call a ``fwd_*`` helper AND are reachable from ``main.rs``.
"""

from __future__ import annotations

import ast
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "development" / "rust-migration-inventory.yaml"
ROUTE_METHODS = {"route", "get", "post", "put", "delete", "patch"}
SHORTHAND_METHODS = {name: [name.upper()] for name in ROUTE_METHODS - {"route"}}
NATIVE_ROUTES = {
    # Ported in v4.631.0; without these two lines the inventory keeps calling
    # them "proxied" forever, which is the rot the module docstring warns about.
    ("/api/sweep/info/<int:file_id>", ("GET",)),
    ("/api/sweep/files/<sweep_id>", ("GET",)),
    # Ported in v4.633.0 — the /help page pair was rendering an empty TOC and
    # /help/<section> had no Rust route at all (404 in standalone).
    ("/help/<section>", ("GET",)),
    ("/_pin", ("GET",)),
    ("/_pin_check", ("POST",)),
    ("/api/lock/activate", ("POST",)),
    ("/api/lock/unlock", ("POST",)),
    ("/api/lock/status", ("GET",)),
    ("/api/auth/status", ("GET",)),
    ("/api/auth/logout", ("POST",)),
    ("/api/files", ("GET",)),
    ("/api/files/<file_id>/tags", ("GET", "POST")),
    ("/api/files/<file_id>/tags/<tag_id>", ("DELETE",)),
    ("/api/scan/status", ("GET",)),
    ("/api/ratings/get", ("GET",)),
    ("/api/ratings/stats", ("GET",)),
    ("/api/help/toc", ("GET",)),
    ("/api/help/search", ("GET",)),
    ("/api/settings/llm-endpoints", ("GET",)),
    ("/api/ui/list", ("GET",)),
}
NATIVE_BATCHES = {
    ("/api/ratings/get", ("GET",)): 2,
    ("/api/ratings/stats", ("GET",)): 2,
    ("/api/help/toc", ("GET",)): 2,
    ("/api/help/search", ("GET",)): 2,
    ("/api/settings/llm-endpoints", ("GET",)): 2,
    ("/api/ui/list", ("GET",)): 2,
}
NATIVE_PREFIXES = ("/api/inference/",)


class NoAliasSafeDumper(yaml.SafeDumper):
    def ignore_aliases(self, data: object) -> bool:
        return True


@dataclass(frozen=True)
class ExtractionResult:
    routes: list[dict[str, Any]]
    skipped: int


def core_deps_for_module(tree: ast.Module) -> list[str]:
    deps = set()
    for node in tree.body:
        if not isinstance(node, ast.ImportFrom):
            continue
        if not node.module or not node.module.startswith("core."):
            continue
        parts = node.module.split(".")
        if len(parts) > 1 and parts[1]:
            deps.add(parts[1])
    return sorted(deps)


def methods_for_decorator(dec: ast.Call, attr: str) -> list[str]:
    if attr != "route":
        return SHORTHAND_METHODS[attr]

    methods = ["GET"]
    for kw in dec.keywords:
        if kw.arg != "methods" or not isinstance(kw.value, ast.List | ast.Tuple):
            continue
        parsed = [
            str(elt.value).upper()
            for elt in kw.value.elts
            if isinstance(elt, ast.Constant) and isinstance(elt.value, str)
        ]
        if parsed:
            methods = parsed
    return methods


def methods_from_keywords(call: ast.Call) -> list[str]:
    for kw in call.keywords:
        if kw.arg != "methods" or not isinstance(kw.value, ast.List | ast.Tuple):
            continue
        parsed = [
            str(elt.value).upper()
            for elt in kw.value.elts
            if isinstance(elt, ast.Constant) and isinstance(elt.value, str)
        ]
        if parsed:
            return parsed
    return ["GET"]


def name_from_expr(expr: ast.expr | None) -> str:
    if isinstance(expr, ast.Name):
        return expr.id
    if isinstance(expr, ast.Attribute):
        return expr.attr
    if isinstance(expr, ast.Constant) and isinstance(expr.value, str):
        return expr.value
    return ""


def route_identity(route: dict[str, Any]) -> tuple[str, tuple[str, ...]]:
    return (route["path"], tuple(sorted(route["methods"])))


def make_route(
    *,
    path: str,
    methods: list[str],
    handler: str,
    py: Path,
    root: Path,
    core_deps: list[str],
) -> dict[str, Any]:
    return {
        "path": path,
        "methods": methods,
        "handler": handler,
        "file": str(py.relative_to(root)),
        "core_deps": core_deps,
        "status": "proxied",
        "batch": None,
    }


def extract_decorator_route(
    dec: ast.Call,
    node: ast.FunctionDef | ast.AsyncFunctionDef,
    py: Path,
    root: Path,
    core_deps: list[str],
) -> dict[str, Any] | None:
    if not isinstance(dec.func, ast.Attribute):
        return None
    attr = dec.func.attr
    if attr not in ROUTE_METHODS:
        return None
    if (
        not dec.args
        or not isinstance(dec.args[0], ast.Constant)
        or not isinstance(dec.args[0].value, str)
    ):
        return None
    return make_route(
        path=dec.args[0].value,
        methods=methods_for_decorator(dec, attr),
        handler=node.name,
        py=py,
        root=root,
        core_deps=core_deps,
    )


def extract_add_url_rule_route(
    call: ast.Call,
    py: Path,
    root: Path,
    core_deps: list[str],
) -> dict[str, Any] | None:
    if not isinstance(call.func, ast.Attribute) or call.func.attr != "add_url_rule":
        return None
    if (
        not call.args
        or not isinstance(call.args[0], ast.Constant)
        or not isinstance(call.args[0].value, str)
    ):
        return None

    view_func: ast.expr | None = None
    if len(call.args) >= 3:
        view_func = call.args[2]
    for kw in call.keywords:
        if kw.arg == "view_func":
            view_func = kw.value
            break

    return make_route(
        path=call.args[0].value,
        methods=methods_from_keywords(call),
        handler=name_from_expr(view_func),
        py=py,
        root=root,
        core_deps=core_deps,
    )


def extract_routes(py: Path, root: Path = ROOT) -> ExtractionResult:
    tree = ast.parse(py.read_text(encoding="utf-8"), filename=str(py))
    core_deps = core_deps_for_module(tree)
    routes: list[dict[str, Any]] = []
    skipped = 0

    for node in ast.walk(tree):
        if not isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
            continue
        for dec in node.decorator_list:
            if not isinstance(dec, ast.Call) or not isinstance(dec.func, ast.Attribute):
                continue
            attr = dec.func.attr
            if attr not in ROUTE_METHODS:
                continue
            route = extract_decorator_route(dec, node, py, root, core_deps)
            if route is None:
                skipped += 1
                continue
            routes.append(route)

    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        route = extract_add_url_rule_route(node, py, root, core_deps)
        if route is not None:
            routes.append(route)
        elif isinstance(node.func, ast.Attribute) and node.func.attr == "add_url_rule":
            skipped += 1

    return ExtractionResult(routes=routes, skipped=skipped)


def apply_existing_metadata(
    routes: list[dict[str, Any]], old_doc: dict[str, Any] | None
) -> None:
    if not old_doc:
        return
    old = {
        route_identity(entry): entry
        for entry in old_doc.get("routes", [])
        if isinstance(entry, dict) and "path" in entry and "methods" in entry
    }
    for route in routes:
        prev = old.get(route_identity(route))
        if prev:
            route["status"] = prev.get("status", route["status"])
            route["batch"] = prev.get("batch", route["batch"])


def mark_native_routes(routes: list[dict[str, Any]]) -> None:
    for route in routes:
        identity = route_identity(route)
        if identity in NATIVE_ROUTES or (
            route["path"].startswith(NATIVE_PREFIXES) and route["status"] == "proxied"
        ):
            route["status"] = "native"
        if identity in NATIVE_BATCHES:
            route["batch"] = NATIVE_BATCHES[identity]


def load_existing_doc() -> dict[str, Any] | None:
    if not OUT.exists():
        return None
    return yaml.safe_load(OUT.read_text(encoding="utf-8")) or {}


def has_app_level_registration(path: Path) -> bool:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in ast.walk(tree):
        if (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and node.func.attr == "add_url_rule"
        ):
            return True
        if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
            for dec in node.decorator_list:
                if (
                    isinstance(dec, ast.Call)
                    and isinstance(dec.func, ast.Attribute)
                    and dec.func.attr == "route"
                    and isinstance(dec.func.value, ast.Name)
                    and dec.func.value.id == "app"
                ):
                    return True
    return False


def route_files(root: Path = ROOT) -> list[Path]:
    files = {
        path
        for path in (root / "routes").rglob("*.py")
        if "__pycache__" not in path.parts
    }
    core_root = root / "core"
    if core_root.exists():
        files.update(
            path
            for path in core_root.rglob("*.py")
            if "__pycache__" not in path.parts and has_app_level_registration(path)
        )
    web_ui = root / "web_ui.py"
    if web_ui.exists() and has_app_level_registration(web_ui):
        files.add(web_ui)
    return sorted(files)


def build_inventory(root: Path = ROOT) -> tuple[dict[str, Any], int]:
    routes: list[dict[str, Any]] = []
    skipped = 0
    for py in route_files(root):
        result = extract_routes(py, root)
        routes.extend(result.routes)
        skipped += result.skipped

    apply_existing_metadata(routes, load_existing_doc())
    mark_native_routes(routes)
    native = sum(1 for route in routes if route["status"] == "native")
    method_counts = dict(sorted(Counter(m for r in routes for m in r["methods"]).items()))
    return (
        {
            "total": len(routes),
            "native": native,
            "method_counts": method_counts,
            "skipped_non_constant_paths": skipped,
            "routes": routes,
        },
        skipped,
    )


def main() -> None:
    doc, skipped = build_inventory()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        yaml.dump(
            doc,
            Dumper=NoAliasSafeDumper,
            allow_unicode=True,
            sort_keys=False,
        ),
        encoding="utf-8",
    )
    print(
        f"{doc['total']} routes, {doc['native']} native -> {OUT} "
        f"({skipped} non-constant paths skipped)"
    )


if __name__ == "__main__":
    main()
