"""Migrate launch-args.txt (Python era) to ~/.config/yu/server.env (Rust era).

Usage:
    uv run python scripts/migrate_launch_args.py
    uv run python scripts/migrate_launch_args.py --input /path/to/launch-args.txt
    uv run python scripts/migrate_launch_args.py --output /path/to/server.env
    uv run python scripts/migrate_launch_args.py --force   # overwrite existing
    uv run python scripts/migrate_launch_args.py --dry-run # print only
"""

import argparse
import os
import shlex
import sys
from pathlib import Path

# Python-arg → (YU_env_var, note_if_skipped)
ARG_MAP: dict[str, tuple[str, str]] = {
    "--db":     ("YU_DB",     ""),
    "--host":   ("YU_HOST",   ""),
    "--port":   ("YU_PORT",   ""),
    "--pin":    ("YU_PIN",    ""),
    "--config": ("YU_CONFIG", ""),
}

# flags (no value) that expand to env assignments
FLAG_MAP: dict[str, tuple[str, str]] = {
    "--lan": ("YU_HOST", "0.0.0.0"),
}

# Python-only args with no Rust equivalent — warn and skip
SKIP = {
    "--allow-restart", "--allow-remote-restart", "--restart-token",
    "--debug", "--debug-log", "--debug-log-file", "--debug-log-max-mb",
    "--debug-log-backups", "--debug-log-stdout",
    "--mode", "--headless", "--safe-mode", "--profile",
    "--trusted-proxy-auth",
}

# Old env vars → new env vars
ENV_MAP: dict[str, str] = {
    "TAGDB_DB":     "YU_DB",
    "TAGDB_CONFIG": "YU_CONFIG",
    "YU_TAURI_PIN": "YU_PIN",
}


def load_launch_args(path: Path) -> list[str]:
    tokens: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            tokens.extend(shlex.split(line))
    return tokens


def parse_args(tokens: list[str]) -> tuple[dict[str, str], list[str]]:
    """Return (env_assignments, skipped_args)."""
    env: dict[str, str] = {}
    skipped: list[str] = []
    i = 0
    while i < len(tokens):
        tok = tokens[i]
        if tok in FLAG_MAP:
            var, val = FLAG_MAP[tok]
            env[var] = val
        elif tok in ARG_MAP:
            if i + 1 >= len(tokens):
                print(f"[WARN] {tok}: missing value, skipped", file=sys.stderr)
                i += 1
                continue
            var, _ = ARG_MAP[tok]
            env[var] = tokens[i + 1]
            i += 1
        elif tok in SKIP:
            skipped.append(tok)
            # consume value if present
            if i + 1 < len(tokens) and not tokens[i + 1].startswith("--"):
                i += 1
        else:
            print(f"[WARN] unknown arg '{tok}', skipped", file=sys.stderr)
        i += 1
    return env, skipped


def collect_old_envs() -> dict[str, str]:
    found: dict[str, str] = {}
    for old, new in ENV_MAP.items():
        val = os.environ.get(old)
        if val:
            found[new] = val
    return found


def _quote_env_val(val: str) -> str:
    """Double-quote a value so backslashes in Windows paths are not misread as escape sequences."""
    escaped = val.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render(env: dict[str, str]) -> str:
    lines = [
        "# yu-server environment — generated by scripts/migrate_launch_args.py",
        "# Keep this file chmod 600 (YU_DB_KEY is sensitive).",
        "",
    ]
    for key, val in env.items():
        lines.append(f"{key}={_quote_env_val(val)}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--input",   default="launch-args.txt", help="Source launch-args.txt")
    p.add_argument("--output",  default=str(Path.home() / ".config/yu/server.env"), help="Destination server.env")
    p.add_argument("--force",   action="store_true", help="Overwrite existing output")
    p.add_argument("--dry-run", action="store_true", help="Print result without writing")
    args = p.parse_args()

    src = Path(args.input)
    dst = Path(args.output)

    # Start with defaults always needed for the Rust server
    env: dict[str, str] = {
        "YU_DB_KEY": "yu-ai-manager-v1-cipher-2026",
    }

    # 1. Old env vars
    env.update(collect_old_envs())

    # 2. launch-args.txt
    skipped: list[str] = []
    if src.exists():
        tokens = load_launch_args(src)
        file_env, skipped = parse_args(tokens)
        env.update(file_env)
        print(f"[OK] read {src}")
    else:
        print(f"[INFO] {src} not found — using env vars only")

    if skipped:
        print(f"[SKIP] Python-only args (no Rust equivalent): {', '.join(sorted(set(skipped)))}")

    content = render(env)

    if args.dry_run:
        print("\n--- server.env (dry-run) ---")
        print(content)
        return

    if dst.exists() and not args.force:
        print(f"[ERROR] {dst} already exists. Use --force to overwrite.", file=sys.stderr)
        sys.exit(1)

    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(content, encoding="utf-8")
    dst.chmod(0o600)
    print(f"[OK] wrote {dst} (chmod 600)")
    print()
    print("Next steps:")
    print(f"  1. Review {dst} and set YU_DB to the correct absolute path")
    print("  2. Install service: cp deploy/yu-server.service ~/.config/systemd/user/")
    print("  3. systemctl --user daemon-reload && systemctl --user enable --now yu-server")


if __name__ == "__main__":
    main()
