#!/usr/bin/env bash
# gen-compose.sh — Generate docker-compose.override.yml with safe defaults
#
# Usage:
#   ./tools/gen-compose.sh              # local only (127.0.0.1:5000)
#   ./tools/gen-compose.sh --lan        # LAN access  (0.0.0.0:5000)
#   ./tools/gen-compose.sh --port 8080  # custom port
#   ./tools/gen-compose.sh --lan --port 8080 --pin 1234
#
# Output: docker-compose.override.yml (git-ignored, user-specific)
set -euo pipefail

HOST="127.0.0.1"
PORT="5000"
PIN=""
LAN=false
HAILO=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --lan)       LAN=true;  HOST="0.0.0.0"; shift ;;
    --port)      PORT="$2";  shift 2 ;;
    --pin)       PIN="$2";   shift 2 ;;
    --hailo)     HAILO=true; shift ;;
    -h|--help)
      echo "Usage: $0 [--lan] [--port PORT] [--pin PIN] [--hailo]"
      echo ""
      echo "Generates docker-compose.override.yml with safe defaults."
      echo ""
      echo "Options:"
      echo "  --lan         Bind to 0.0.0.0 (accessible from LAN). Default: 127.0.0.1"
      echo "  --port PORT   Host port to expose. Default: 5000"
      echo "  --pin PIN     Require PIN authentication"
      echo "  --hailo       Show Hailo-10H startup guide"
      echo "  -h, --help    Show this help"
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

# Build command args
CMD_ARGS='["python", "web_ui.py", "--db", "/app/data/tags.db", "--host", "'"$HOST"'"'
if $LAN; then
  CMD_ARGS="$CMD_ARGS"', "--lan"'
fi
if [[ -n "$PIN" ]]; then
  CMD_ARGS="$CMD_ARGS"', "--pin", "'"$PIN"'"'
fi
CMD_ARGS="$CMD_ARGS]"

# Port binding: when local-only, bind to 127.0.0.1 on host side too
if $LAN; then
  PORT_BIND="\"${PORT}:5000\""
else
  PORT_BIND="\"127.0.0.1:${PORT}:5000\""
fi

OUTPUT="docker-compose.override.yml"

cat > "$OUTPUT" <<YAML
# Auto-generated by tools/gen-compose.sh — do not edit manually
# Re-run: ./tools/gen-compose.sh$(if $LAN; then echo " --lan"; fi)$(if [[ "$PORT" != "5000" ]]; then echo " --port $PORT"; fi)$(if [[ -n "$PIN" ]]; then echo " --pin $PIN"; fi)
#
# Bind: ${HOST}:${PORT}
services:
  yu-ai-manager:
    ports:
      - ${PORT_BIND}
    command: ${CMD_ARGS}
YAML

echo "Generated ${OUTPUT}"
echo "  Bind: ${HOST}:${PORT}"
if $LAN; then
  echo "  ⚠  LAN access enabled (0.0.0.0)"
else
  echo "  ✓ Local only (127.0.0.1)"
fi
if [[ -n "$PIN" ]]; then
  echo "  🔒 PIN auth enabled"
fi
echo ""
if $HAILO; then
  echo "To enable Hailo-10H:"
  echo "  docker compose -f docker-compose.yml -f docker-compose.hailo.yml up yu-ai-manager"
  echo ""
  echo "Build the image with the Hailo variant first:"
  echo "  ./tools/docker-build.sh --hailo --hailo-wheel <path-to-.whl>"
  echo ""
else
  echo "Run:  docker compose up yu-ai-manager"
fi
